# Generated by Django 5.2.6 on 2025-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '블로그', 'verbose_name_plural': '블로그 목록'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='context',
            new_name='content',
        ),
    ]
